### ISSUE TITLE
Auth page goes 401

### ISSUE THREAD

**Issue by mrgaolei** [timdorr/tesla-api#548]
https://owner-api.teslamotors.com/oauth/token
response:
```json
{
"error":"unsupported_grant_type",
"error_description":"The authorization grant type is not supported by the authorization server."
}
```
from 2022-3-22, before this day everything is OK.

And then, how to change token?

UPDATE:
At now, step 3 `https://auth.tesla.com/oauth2/v3/token` return access_token can be access all API endpoint.
No need step 4 yet.
But all token expire in 8 hours.
And `refresh_token` not working.
Who knew how to refresh token?

UPDATE 2:
refresh token does work now.
All things done.

**Comment by slk1107** [comment]
Getting same stuff here. The Tesla API in iOS App cannot be reversed by middle man. Is there any other way to get the latest grant_type?

**Comment by TA2k** [comment]
They removed the owner Token only the normal access token is now working for all endpoints. 
A long overdue decision, as it is far too unsecure to keep a token valid for such a long time.

**Comment by teslastruggler** [comment]
> They removed the owner Token only the normal access token is now working for all endpoints. A long overdue decision, as it is far too unsecure to keep a token valid for such a long time.

Apologies, what does this mean we have to change in our code? I cannot find "owner token" or "normal access token" in the documentation or code.

**Comment by mrgaolei** [comment]
> They removed the owner Token only the normal access token is now working for all endpoints. A long overdue decision, as it is far too unsecure to keep a token valid for such a long time.

Do you know how to refresh token?

**Comment by itsMeDavidV** [comment]
> They removed the owner Token only the normal access token is now working for all endpoints. 

Active qts- tokens still work, just can't generate new ones. Guessing this is a phase out?

**Comment by TA2k** [comment]
Yes the last Owner/qts Token will expire in 22.03.2022 + 45 days

The process for receiving and refreshing the access token is well documented
https://github.com/timdorr/tesla-api/blob/master/docs/api-basics/authentication.md#post-httpsauthteslacomoauth2v3token

Refreshing:
https://github.com/timdorr/tesla-api/blob/master/docs/api-basics/authentication.md#refreshing-an-access-token

**Comment by teslastruggler** [comment]
Yes we have all followed this documentation, but as the first message in this issue, and messages on many of the discussion threads says - something has changed and now Step 4 doesn’t work.  

The first message in this thread shows someone trying Step 4 in the documentation and the error message. 

If you know how to fix this I would be grateful if you could help - what is the ‘normal’ access token?

**Comment by TA2k** [comment]
As the first message mentioned:
No step 4 needed.
Step 4 is deprecated and removed by Tesla
Normal token is the token from Step 3

**Comment by dacastro4** [comment]
My refreshing process was working before these changes.
Now I'm getting ```{"error":"invalid_request","error_description":"Invalid resource","error_uri":"https://auth.tesla.com/error/reference/164d839d-06e2-4d5c-8110-9fecd07b3f3a-1647987570635"}```
@mrgaolei are you getting the same thing?

**Comment by brianflex** [comment]
@dacastro4 When refreshing, if you had code that tried exchanging an access code for a bearer token, that doesn't seem necessary anymore.  You get back a bearer token from an earlier part of the process.

**Comment by brianflex** [comment]
Does anyone know how long the refresh token is valid for now?  8 hours?  45 days still?  The response from Tesla only provides one expires_in value.

**Comment by dacastro4** [comment]
> @dacastro4 When refreshing, if you had code that tried exchanging an access code for a bearer token, that doesn't seem necessary anymore. You get back a bearer token from an earlier part of the process.

Sorry if I don't understand. Are you talking about the refreshing process? My issue is when I'm trying to refresh the token. If I post to the URL I get the invalid resource error

**Comment by briangru** [comment]
@dacastro4 Take a look at this PR.  In the same way that one step was removed from authentication, it looks like we can skip the last step when refreshing tokens too.  https://github.com/tomhollander/TeslaAuth/pull/25

**Comment by dacastro4** [comment]
> @dacastro4 Take a look at this PR. In the same way that one step was removed from authentication, it looks like we can skip the last step when refreshing tokens too. [tomhollander/TeslaAuth#25](https://github.com/tomhollander/TeslaAuth/pull/25)

Ohh yeah, I know what you are talking about now. Yes, we can remove that step from the logic but the issue still is that the refresh endpoint itself is failing.

**Comment by slk1107** [comment]
> 

The refreshed token last for 8 hours too.

**Comment by briangru** [comment]
Note on the refresh token - I waited over 10 hours, used the refresh token and got back a new access token.  And the refresh token I got back was identical to the one I passed in.  It seems that the lifetime of the refresh token is decoupled from the access token's lifetime, which is great.  It doesn't give us any hint about how long the refresh token is good for, but it's something.

**Comment by BJReplay** [comment]
Thanks @briangru for your comment on the refresh token not changing - I was beginning to think I was doing something wrong as I was getting back the same refresh token.

**Comment by briangru** [comment]
@BJReplay I'm glad I'm not the only one who saw that.  However, this is just what Tesla's servers do today, and is not necessarily what they will do in the future.  It's hard conceptually to deal with refresh tokens with _potentially_ no known expiration time.  Maybe they last for forever, until someone changes a password to revoke them?  Or maybe they will be updated on day 44 during the next refresh of the access token.  And if you have an old expired token you can't easily identify it.
Might be worth holding onto a refresh token for 45 days and seeing what happens.

**Comment by dacastro4** [comment]
> Note on the refresh token - I waited over 10 hours, used the refresh token and got back a new access token. And the refresh token I got back was identical to the one I passed in. It seems that the lifetime of the refresh token is decoupled from the access token's lifetime, which is great. It doesn't give us any hint about how long the refresh token is good for, but it's something.

Do you mind sharing with me the request that you made to refresh the token?

**Comment by haha150** [comment]
> > Note on the refresh token - I waited over 10 hours, used the refresh token and got back a new access token. And the refresh token I got back was identical to the one I passed in. It seems that the lifetime of the refresh token is decoupled from the access token's lifetime, which is great. It doesn't give us any hint about how long the refresh token is good for, but it's something.
> 
> Do you mind sharing with me the request that you made to refresh the token?

Hi,

You do this exact request: https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token

New thing is that you MUST use the new tokens generated after March 21

**Comment by dacastro4** [comment]
> > > Note on the refresh token - I waited over 10 hours, used the refresh token and got back a new access token. And the refresh token I got back was identical to the one I passed in. It seems that the lifetime of the refresh token is decoupled from the access token's lifetime, which is great. It doesn't give us any hint about how long the refresh token is good for, but it's something.
> > 
> > 
> > Do you mind sharing with me the request that you made to refresh the token?
> 
> Hi,
> 
> You do this exact request: https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token
> 
> New thing is that you MUST use the new tokens generated after March 21, for the request above

This is exactly what I'm using and keep getting 
```{"error":"invalid_request","error_description":"Invalid resource","error_uri":"https://auth.tesla.com/error/reference/164d839d-06e2-4d5c-8110-9fecd07b3f3a-1647987570635"}
```
Sorry to keep asking I just don't know what changed for this not to work.

**Comment by haha150** [comment]
> 

for me, i do the following:

- Set header, Content-Type: application/json
- POST on https://auth.tesla.com/oauth2/v3/token
with the data body
{
  "grant_type": "refresh_token",
  "client_id": "ownerapi",
  "refresh_token": "eyJrefresh", //this token is from Step 3 in the documentation
  "scope": "openid email offline_access"
}

**Comment by dacastro4** [comment]
> 

Thank you! It's not working for me for some weird reason

**Comment by dacastro4** [comment]
@mrgaolei were you getting the same issue when trying to refresh? If so, what did you do to fix it?

**Comment by joshendy** [comment]
Anyone having trouble with step 3? Suddenly stopped working for me (getting 403 forbidden) at the same time this at the same time as the owner token being phased out. I'm passing the following to /oauth2/v3/token:
{
"grant_type": "authorization_code",
"client_id": "ownerapi",
"code": "code goes here",
"code_verifier": "verifier goes here",
"redirect_uri": "https://auth.tesla.com/void/callback"
}

Response body of the 403 is: "{"error":"invalid_grant","error_description":"Internal server error", "error_uri":"..."}"

**Comment by mrgaolei** [comment]
> 

refresh token API not change.

**Comment by stevieb9** [comment]
> Does anyone know how long the refresh token is valid for now? 8 hours? 45 days still? The response from Tesla only provides one expires_in value.

When I fetch the token, I take `expires_in` as soon as I get the new token, add the current time to it, then write it back as `expires_at`, and use that new attribute when checking validity.

**Comment by Panda88CO** [comment]
> > > > Note on the refresh token - I waited over 10 hours, used the refresh token and got back a new access token. And the refresh token I got back was identical to the one I passed in. It seems that the lifetime of the refresh token is decoupled from the access token's lifetime, which is great. It doesn't give us any hint about how long the refresh token is good for, but it's something.
> > > 
> > > 
> > > Do you mind sharing with me the request that you made to refresh the token?
> > 
> > 
> > Hi,
> > You do this exact request: https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token
> > New thing is that you MUST use the new tokens generated after March 21, for the request above
> 
> This is exactly what I'm using and keep getting
> 
> ```
> {"error":"invalid_request","error_description":"Invalid resource","error_uri":"https://auth.tesla.com/error/reference/164d839d-06e2-4d5c-8110-9fecd07b3f3a-1647987570635"}
> ```
> 
> Sorry to keep asking I just don't know what changed for this not to work.

If you copy and paste token - make sure there is not an empty space at the end - I had the same issue

**Comment by psmedley** [comment]
> > 
> 
> for me, i do the following:
> 
> * Set header, Content-Type: application/json
> * POST on https://auth.tesla.com/oauth2/v3/token
>   with the data body
>   {
>   "grant_type": "refresh_token",
>   "client_id": "ownerapi",
>   "refresh_token": "eyJrefresh", //this token is from Step 3 in the documentation
>   "scope": "openid email offline_access"
>   }

Is it just  me, or is the response now missing an updated "refresh_token"?

The documentation suggests  the response should be:
`{
  "access_token": "eyJaccess",
  "refresh_token": "eyJrefresh",
  "id_token": "id",
  "expires_in": 300,
  "token_type": "Bearer"
}`
But I'm just seeing:
`{
  "access_token": "eyJaccess",
  "id_token": "id",
  "expires_in": 300,
  "token_type": "Bearer"
}`

I'm using the following command for testing, in order to work out what I need to do to fix my OpenHAB binding, which was previously just using the 45 day expiry access_tokens:
`curl --include --data "grant_type=refresh_token&client_id=ownerapi&refresh_token=eyXXXXXX&scope='openid email offline_access'" --request POST 'https://auth.tesla.com/oauth2/v3/token'
`

**Comment by stevieb9** [comment]
> > > 
> > 
> > 
> > for me, i do the following:
> > 
> > * Set header, Content-Type: application/json
> > * POST on https://auth.tesla.com/oauth2/v3/token
> >   with the data body
> >   {
> >   "grant_type": "refresh_token",
> >   "client_id": "ownerapi",
> >   "refresh_token": "eyJrefresh", //this token is from Step 3 in the documentation
> >   "scope": "openid email offline_access"
> >   }
> 
> Is it just me, or is the response now missing an updated "refresh_token"?
> 
> The documentation suggests the response should be: `{ "access_token": "eyJaccess", "refresh_token": "eyJrefresh", "id_token": "id", "expires_in": 300, "token_type": "Bearer" }` But I'm just seeing: `{ "access_token": "eyJaccess", "id_token": "id", "expires_in": 300, "token_type": "Bearer" }`
> 
> I'm using the following command for testing, in order to work out what I need to do to fix my OpenHAB binding, which was previously just using the 45 day expiry access_tokens: `curl --include --data "grant_type=refresh_token&client_id=ownerapi&refresh_token=eyXXXXXX&scope='openid email offline_access'" --request POST 'https://auth.tesla.com/oauth2/v3/token' `

I got the same thing. The refresh token stays valid, so I simply re-add the original one back in before saving the JSON data. I only get a new refresh token on initial access token generation.

**Comment by psmedley** [comment]
> I got the same thing. The refresh token stays valid, so I simply re-add the original one back in before saving the JSON data. I only get a new refresh token on initial access token generation.

thanks - do we know how long the refresh tokens are valid for?

**Comment by SylvainGa** [comment]
> > > > 
> > > 
> > > 
> > > for me, i do the following:
> > > 
> > > * Set header, Content-Type: application/json
> > > * POST on https://auth.tesla.com/oauth2/v3/token
> > >   with the data body
> > >   {
> > >   "grant_type": "refresh_token",
> > >   "client_id": "ownerapi",
> > >   "refresh_token": "eyJrefresh", //this token is from Step 3 in the documentation
> > >   "scope": "openid email offline_access"
> > >   }
> > 
> > 
> > Is it just me, or is the response now missing an updated "refresh_token"?
> > The documentation suggests the response should be: `{ "access_token": "eyJaccess", "refresh_token": "eyJrefresh", "id_token": "id", "expires_in": 300, "token_type": "Bearer" }` But I'm just seeing: `{ "access_token": "eyJaccess", "id_token": "id", "expires_in": 300, "token_type": "Bearer" }`
> > I'm using the following command for testing, in order to work out what I need to do to fix my OpenHAB binding, which was previously just using the 45 day expiry access_tokens: `curl --include --data "grant_type=refresh_token&client_id=ownerapi&refresh_token=eyXXXXXX&scope='openid email offline_access'" --request POST 'https://auth.tesla.com/oauth2/v3/token' `
> 
> I got the same thing. The refresh token stays valid, so I simply re-add the original one back in before saving the JSON data. I only get a new refresh token on initial access token generation.

I mentioned this in #551 but for me, it started working again about an hour later. I'm getting a refresh token as part of the answer. Did nothing different. I thought it was a transient error that was fixed, but I guess not if others are also seeing this issue.

**Comment by dacastro4** [comment]
> 

I used your curl and I keep getting

```
curl --include --data "grant_type=refresh_token&client_id=ownerapi&refresh_token=eyJhbxxxx&scope='openid email offline_access'" --request POST 'https://auth.tesla.com/oauth2/v3/token'
````

Response:

```
HTTP/2 400
content-type: application/json
content-length: 170
x-dns-prefetch-control: off
x-frame-options: DENY
strict-transport-security: max-age=15552000; includeSubDomains
x-download-options: noopen
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-request-id: 7fd2c28d-ec0c-4053-887f-3c1216593d3b
x-correlation-id: 7fd2c28d-ec0c-4053-887f-3c1216593d3b
cache-control: no-store
access-control-allow-origin: *
x-response-time: 21.737ms
x-edgeconnect-midmile-rtt: 31
x-edgeconnect-origin-mex-latency: 95
date: Mon, 28 Mar 2022 23:07:36 GMT
permissions-policy: interest-cohort=()
set-cookie: _abck=xxx; Domain=.tesla.com; Path=/; Expires=Tue, 28 Mar 2023 23:07:36 GMT; Max-Age=31536000; Secure
set-cookie: bm_sz=xxx; Domain=.tesla.com; Path=/; Expires=Tue, 29 Mar 2022 03:07:36 GMT; Max-Age=14400

{"error":"invalid_request","error_description":"Invalid resource","error_uri":"https://auth.tesla.com/error/reference/7fd2c28d-ec0c-4053-887f-3c1216593d3b-1648508856355"}
```

And I still don't understand why

**Comment by psmedley** [comment]
Curl v7.81.0 works for me, curl v7.74.0 on another system gives me a 403 error and an Access Denied error.

**Comment by dacastro4** [comment]
> Curl v7.81.0 works for me, curl v7.74.0 on another system gives me a 403 error and an Access Denied error. I assume you replaced eyJhbxxxx with a valid SSO Refresh token?

For me, it doesn't matter what I use, it doesn't work. I've tried with Postman, curl, and my application without success. My app was previously working before the tokens changes happened.

**Comment by timdorr** [comment]
Closing this since it looks like the temporary issue was resolved.
